import type { Language } from "./types";
const en = {
  chat: "Workspace", knowledge: "Knowledge", timetable: "Timetable", profile: "My context", newChat: "New conversation", recent: "Recent conversations", noHistory: "A fresh start", today: "YOUR STUDY SPACE", greeting: "What are we exploring,", subtitle: "Your school. Your context. Your next idea.",
  school: "School", grade: "Grade", demo: "Demo profile", simulated: "Simulated school context", schoolDay: "My school day", contextReady: "Context ready", connected: "School materials connected", noMaterials: "No school materials yet", addMaterials: "Add materials", files: "files", ready: "Ready", setup: "AI not connected", setupNote: "AI is not connected yet. The workspace is ready; ask the demo administrator to finish setup.",
  placeholder: "Ask a question, explore an idea, or attach a task…", send: "Send message", stop: "Stop generation", image: "Attach an image", camera: "Take a photo", attach: "Attach a document", remove: "Remove attachment", trilingua: "TriLingua", web: "Search web", schoolOnly: "School sources", auto: "All knowledge", inputNote: "School-aware. Source-clear. Always curious.",
  physics: "Physics", maths: "Mathematics", history: "History", computer: "Computer science", english: "English", tomorrow: "Tomorrow", inFourDays: "In 4 days", assessment: "Physics assessment", project: "History project", induction: "Electromagnetic induction", derivatives: "Derivatives", practice: "Needs practice", strong: "Looking strong", upcoming: "Coming up", learning: "Learning focus", subjects: "My subjects", viewContext: "View my context",
  prepare: "Make a study plan", prepareSub: "A little direction for today", explain: "Make it click", explainSub: "One idea, three languages", scan: "Scan a task", scanSub: "Start with a photo", askNis: "Ask about NIS", askNisSub: "Answers from your materials", recommended: "YOUR NEXT STEP", physicsAction: "Get ready for Physics", physicsSub: "Electromagnetic induction", start: "Let's begin", minutes: "20 min focus",
  planPrompt: "What should I study now?", explainPrompt: "Explain electromagnetic induction simply in English, and show the key terms in Kazakh and Russian.", physicsPrompt: "Help me prepare for my Physics assessment on electromagnetic induction. Start with a short explanation, then ask me a practice question.", nisPrompt: "What school assessment rules are described in the uploaded NIS materials?", photoPrompt: "Help me understand and solve the task in this image.",
  libraryTitle: "A little knowledge goes a long way.", librarySub: "Your educational materials", upload: "Upload material", uploadHint: "PDF, DOCX, TXT, MD · up to 8 MB", emptyLibrary: "Your library starts here", emptyLibrarySub: "Add a lesson, a textbook chapter, or your class notes.", indexing: "Indexing", failed: "Indexing failed", deleteFile: "Delete material", searchLibrary: "Find a material…", uploaded: "Uploaded materials", schoolLibrary: "School collection", schoolLibrarySub: "Administrator-managed NIS materials", noResults: "No matching materials", sample: "Download sample Physics notes", sampleLabel: "Sample lesson · not official NIS material", askFile: "Ask about this", filePrompt: "Summarize the key ideas in", confirmDelete: "Delete this material?", cancel: "Cancel", delete: "Delete", refresh: "Refresh materials",
  profileTitle: "A workspace that knows you.", profileSub: "Your school context", name: "First name", preferred: "Preferred language", save: "Save context", saved: "Context saved", reset: "Reset demo profile", mockNote: "This student profile and school agenda are simulated. No school system is connected.", aboutYou: "About you", clearHistory: "Clear conversation history", confirmClear: "Clear all conversations in this browser session?", theme: "Change color theme", menu: "Open navigation", close: "Close", back: "Back to workspace", you: "You", searching: "Looking through sources…", thinking: "Thinking…", sessionUsage: "Session API tokens", input: "input", output: "output", language: "Language", timetableTitle: "Timetable", timetableSubtitle: "Current lessons from EduPage", week: "Week", openEdupage: "Open in EduPage", selectClass: "Select your class", continue: "Continue", currentLesson: "Current lesson", nextLesson: "Next lesson", changed: "Changed", cancelled: "Cancelled", substitution: "Substitution", noLessons: "No lessons today.", timetableError: "Unable to load timetable from EduPage.", tryAgain: "Try again", source: "Source", lastRetrieved: "Last retrieved", regularTimetable: "Regular timetable", currentTimetable: "Current timetable", previousWeek: "Previous week", nextWeek: "Next week", received: "Received", authSignIn: "Sign in with Microsoft", authWelcome: "Welcome back", authIntroTitle: "Your school context. Your AI for learning.", authIntroBody: "NIS materials, clear explanations, Teach Me, and everyday study help in one focused space.", authAvailable: "Available for @akt.nis.edu.kz", authPrivacy: "NIS AI never receives your Microsoft school account password.", authAccount: "Account", authSchoolAccount: "Microsoft school account", authConnected: "Connected", authSignOut: "Sign out", authSettings: "My profile", authLoading: "Opening your workspace…", authSetup: "Microsoft sign-in is not configured yet.", authDomainError: "Use your school Microsoft account @akt.nis.edu.kz.", authError: "Microsoft sign-in could not be completed. Try again.",
  uploadError: "The material could not be uploaded. Try again.", fileTooLarge: "Choose a document under 8 MB or an image under 4 MB.", invalidImage: "Choose a valid PNG, JPEG, or WebP image.", invalidFile: "Choose a valid PDF, DOCX, UTF-8 TXT, or MD file.", notConfigured: "AI is not connected. Ask the demo administrator to finish setup.", rateLimited: "Too many requests. Please try again later.", networkError: "Connection interrupted. Please try again.", knowledgeError: "Could not access the materials. Please try again.", limitFiles: "Your library has reached its 12-file limit.", pendingFile: "Wait for this material to finish indexing.", documentAttached: "Material attached", stopped: "Stopped", privacy: "Private session", noImageHistory: "Image not saved; attach it again to retry.",
};
export type Labels = typeof en;
const ru: Labels = {
  chat: "Рабочее пространство", knowledge: "База знаний", timetable: "Расписание", profile: "Мой контекст", newChat: "Новый диалог", recent: "Недавние диалоги", noHistory: "Начнём с чистого листа", today: "ТВОЁ ПРОСТРАНСТВО ДЛЯ УЧЁБЫ", greeting: "Что изучим сегодня,", subtitle: "Твоя школа. Твой контекст. Твои идеи.",
  school: "Школа", grade: "Класс", demo: "Демопрофиль", simulated: "Демонстрационный контекст", schoolDay: "Мой школьный день", contextReady: "Контекст готов", connected: "Материалы школы подключены", noMaterials: "Материалы ещё не добавлены", addMaterials: "Добавить материалы", files: "файлов", ready: "Готово", setup: "ИИ не подключён", setupNote: "ИИ пока не подключён. Пространство готово; попроси администратора завершить настройку.",
  placeholder: "Задай вопрос, поделись идеей или прикрепи задание…", send: "Отправить сообщение", stop: "Остановить генерацию", image: "Прикрепить изображение", camera: "Сделать фото", attach: "Прикрепить документ", remove: "Убрать вложение", trilingua: "TriLingua", web: "Поиск в сети", schoolOnly: "Материалы школы", auto: "Все знания", inputNote: "С контекстом школы. С понятными источниками.",
  physics: "Физика", maths: "Математика", history: "История", computer: "Информатика", english: "Английский", tomorrow: "Завтра", inFourDays: "Через 4 дня", assessment: "СОР по физике", project: "Проект по истории", induction: "Электромагнитная индукция", derivatives: "Производные", practice: "Нужна практика", strong: "Уверенные знания", upcoming: "Ближайшие события", learning: "В фокусе", subjects: "Мои предметы", viewContext: "Открыть мой контекст",
  prepare: "Составить план", prepareSub: "Определим, с чего начать", explain: "Разобраться в теме", explainSub: "Одна идея, три языка", scan: "Разобрать задание", scanSub: "Начни с фотографии", askNis: "Спросить о NIS", askNisSub: "Ответы из твоих материалов", recommended: "ТВОЙ СЛЕДУЮЩИЙ ШАГ", physicsAction: "Подготовимся к физике", physicsSub: "Электромагнитная индукция", start: "Начнём", minutes: "20 минут на тему",
  planPrompt: "Что мне сейчас лучше учить?", explainPrompt: "Объясни electromagnetic induction по-русски, но основные термины покажи на казахском и английском.", physicsPrompt: "Помоги подготовиться к СОР по физике на тему электромагнитной индукции. Сначала коротко объясни тему, затем задай вопрос для практики.", nisPrompt: "Какие правила оценивания описаны в загруженных материалах NIS?", photoPrompt: "Помоги понять и решить задание на этой фотографии.",
  libraryTitle: "Твои материалы. Больше понимания.", librarySub: "Учебная библиотека", upload: "Добавить материал", uploadHint: "PDF, DOCX, TXT, MD · до 8 МБ", emptyLibrary: "Здесь начинается твоя библиотека", emptyLibrarySub: "Добавь урок, главу учебника или конспект.", indexing: "Обработка", failed: "Ошибка обработки", deleteFile: "Удалить материал", searchLibrary: "Найти материал…", uploaded: "Загруженные материалы", schoolLibrary: "Коллекция школы", schoolLibrarySub: "Материалы NIS от администратора", noResults: "Материалы не найдены", sample: "Скачать пример по физике", sampleLabel: "Пример урока · не официальный материал NIS", askFile: "Спросить об этом", filePrompt: "Кратко объясни основные идеи из", confirmDelete: "Удалить этот материал?", cancel: "Отмена", delete: "Удалить", refresh: "Обновить материалы",
  profileTitle: "Пространство, которое тебя знает.", profileSub: "Твой школьный контекст", name: "Имя", preferred: "Предпочитаемый язык", save: "Сохранить контекст", saved: "Контекст сохранён", reset: "Сбросить демопрофиль", mockNote: "Профиль ученика и школьные события созданы для демонстрации. Подключения к школьной системе нет.", aboutYou: "О тебе", clearHistory: "Очистить историю диалогов", confirmClear: "Очистить все диалоги в этой сессии браузера?", theme: "Сменить тему", menu: "Открыть навигацию", close: "Закрыть", back: "Вернуться в диалог", you: "Ты", searching: "Ищем в источниках…", thinking: "Думаем…", sessionUsage: "Токены API за сессию", input: "вход", output: "выход", language: "Язык", timetableTitle: "Расписание", timetableSubtitle: "Актуальные занятия из EduPage", week: "Неделя", openEdupage: "Открыть в EduPage", selectClass: "Выберите свой класс", continue: "Продолжить", currentLesson: "Сейчас", nextLesson: "Следующий урок", changed: "Изменено", cancelled: "Отменено", substitution: "Замена", noLessons: "На сегодня занятий нет.", timetableError: "Не удалось обновить расписание из EduPage.", tryAgain: "Повторить", source: "Источник", lastRetrieved: "Последнее получение", regularTimetable: "Обычное расписание", currentTimetable: "Актуальное расписание", previousWeek: "Предыдущая неделя", nextWeek: "Следующая неделя", received: "Получено", authSignIn: "Войти через Microsoft", authWelcome: "С возвращением", authIntroTitle: "Твой школьный контекст. Твой AI для учёбы.", authIntroBody: "Материалы NIS, понятные объяснения, Teach Me и помощь с учёбой в одном пространстве.", authAvailable: "Доступно для @akt.nis.edu.kz", authPrivacy: "NIS AI не получает пароль от твоей школьной учётной записи Microsoft.", authAccount: "Учётная запись", authSchoolAccount: "Школьная учётная запись Microsoft", authConnected: "Подключено", authSignOut: "Выйти", authSettings: "Мой профиль", authLoading: "Открываем рабочее пространство…", authSetup: "Вход через Microsoft ещё не настроен.", authDomainError: "Используй школьную учётную запись Microsoft @akt.nis.edu.kz.", authError: "Не удалось войти через Microsoft. Попробуй ещё раз.",
  uploadError: "Не удалось загрузить материал. Попробуй ещё раз.", fileTooLarge: "Выбери документ до 8 МБ или изображение до 4 МБ.", invalidImage: "Выбери изображение PNG, JPEG или WebP.", invalidFile: "Выбери корректный PDF, DOCX, TXT в UTF-8 или MD.", notConfigured: "ИИ не подключён. Попроси администратора завершить настройку.", rateLimited: "Слишком много запросов. Попробуй позже.", networkError: "Соединение прервано. Попробуй ещё раз.", knowledgeError: "Не удалось получить материалы. Попробуй ещё раз.", limitFiles: "В библиотеке уже 12 файлов.", pendingFile: "Дождись завершения обработки материала.", documentAttached: "Материал прикреплён", stopped: "Остановлено", privacy: "Личная сессия", noImageHistory: "Фото не сохранено; прикрепи его повторно.",
};
const kk: Labels = {
  chat: "Жұмыс кеңістігі", knowledge: "Білім қоры", timetable: "Сабақ кестесі", profile: "Менің контекстім", newChat: "Жаңа әңгіме", recent: "Соңғы әңгімелер", noHistory: "Жаңа бастама", today: "СЕНІҢ ОҚУ КЕҢІСТІГІҢ", greeting: "Бүгін не үйренеміз,", subtitle: "Сенің мектебің. Сенің контекстің. Сенің идеяларың.",
  school: "Мектеп", grade: "Сынып", demo: "Демопрофиль", simulated: "Демонстрациялық контекст", schoolDay: "Менің мектеп күнім", contextReady: "Контекст дайын", connected: "Мектеп материалдары қосылған", noMaterials: "Материалдар әлі қосылмаған", addMaterials: "Материал қосу", files: "файл", ready: "Дайын", setup: "ЖИ қосылмаған", setupNote: "ЖИ әлі қосылмаған. Кеңістік дайын; әкімшіден баптауды аяқтауды сұра.",
  placeholder: "Сұрақ қой, идеяңмен бөліс немесе тапсырма тірке…", send: "Хабарлама жіберу", stop: "Жауап құруды тоқтату", image: "Сурет тіркеу", camera: "Фото түсіру", attach: "Құжат тіркеу", remove: "Тіркемені алып тастау", trilingua: "TriLingua", web: "Интернеттен іздеу", schoolOnly: "Мектеп материалдары", auto: "Барлық білім", inputNote: "Мектеп контекстімен. Нақты дереккөздермен.",
  physics: "Физика", maths: "Математика", history: "Тарих", computer: "Информатика", english: "Ағылшын тілі", tomorrow: "Ертең", inFourDays: "4 күннен кейін", assessment: "Физикадан БЖБ", project: "Тарих жобасы", induction: "Электромагниттік индукция", derivatives: "Туындылар", practice: "Тәжірибе қажет", strong: "Жақсы меңгерілген", upcoming: "Алдағы оқиғалар", learning: "Назарда", subjects: "Менің пәндерім", viewContext: "Контекстімді ашу",
  prepare: "Оқу жоспарын құру", prepareSub: "Неден бастайтынымызды білейік", explain: "Тақырыпты түсіну", explainSub: "Бір идея, үш тіл", scan: "Тапсырманы талдау", scanSub: "Фотодан баста", askNis: "NIS туралы сұрау", askNisSub: "Материалдарыңнан жауаптар", recommended: "СЕНІҢ КЕЛЕСІ ҚАДАМЫҢ", physicsAction: "Физикаға дайындалайық", physicsSub: "Электромагниттік индукция", start: "Бастайық", minutes: "Тақырыпқа 20 минут",
  planPrompt: "Қазір қай пәнді оқығаным дұрыс?", explainPrompt: "Электромагниттік индукцияны қазақша қарапайым түсіндір, негізгі терминдерді орысша және ағылшынша көрсет.", physicsPrompt: "Электромагниттік индукция тақырыбындағы физика БЖБ-сына дайындалуға көмектес. Алдымен қысқаша түсіндір, содан кейін жаттығу сұрағын қой.", nisPrompt: "Жүктелген NIS материалдарында қандай бағалау ережелері берілген?", photoPrompt: "Осы фотодағы тапсырманы түсінуге және шешуге көмектес.",
  libraryTitle: "Сенің материалдарың. Тереңірек түсінік.", librarySub: "Оқу кітапханасы", upload: "Материал жүктеу", uploadHint: "PDF, DOCX, TXT, MD · 8 МБ дейін", emptyLibrary: "Кітапханаң осы жерден басталады", emptyLibrarySub: "Сабақ, оқулық тарауын немесе конспект қос.", indexing: "Өңделуде", failed: "Өңдеу қатесі", deleteFile: "Материалды жою", searchLibrary: "Материал іздеу…", uploaded: "Жүктелген материалдар", schoolLibrary: "Мектеп жинағы", schoolLibrarySub: "Әкімші қосқан NIS материалдары", noResults: "Материалдар табылмады", sample: "Физикадан үлгі жүктеу", sampleLabel: "Сабақ үлгісі · ресми NIS материалы емес", askFile: "Осы туралы сұрау", filePrompt: "Негізгі идеяларын қысқаша түсіндір:", confirmDelete: "Осы материалды жою керек пе?", cancel: "Бас тарту", delete: "Жою", refresh: "Материалдарды жаңарту",
  profileTitle: "Сені білетін кеңістік.", profileSub: "Сенің мектеп контекстің", name: "Есім", preferred: "Таңдалған тіл", save: "Контекстті сақтау", saved: "Контекст сақталды", reset: "Демопрофильді қалпына келтіру", mockNote: "Оқушы профилі мен мектеп оқиғалары демонстрация үшін жасалған. Мектеп жүйесіне қосылмаған.", aboutYou: "Сен туралы", clearHistory: "Әңгімелер тарихін тазалау", confirmClear: "Осы браузер сессиясындағы барлық әңгімені тазалау керек пе?", theme: "Тақырыпты ауыстыру", menu: "Навигацияны ашу", close: "Жабу", back: "Әңгімеге оралу", you: "Сен", searching: "Дереккөздерден іздеуде…", thinking: "Ойлануда…", sessionUsage: "Сессиядағы API токендері", input: "кіріс", output: "шығыс", language: "Тіл", timetableTitle: "Сабақ кестесі", timetableSubtitle: "EduPage-тен алынған өзекті сабақтар", week: "Апта", openEdupage: "EduPage-те ашу", selectClass: "Сыныбыңды таңда", continue: "Жалғастыру", currentLesson: "Қазір", nextLesson: "Келесі сабақ", changed: "Өзгертілді", cancelled: "Болдырылмады", substitution: "Ауыстыру", noLessons: "Бүгін сабақ жоқ.", timetableError: "EduPage-тен сабақ кестесін жаңарту мүмкін болмады.", tryAgain: "Қайталау", source: "Дереккөз", lastRetrieved: "Соңғы алынған уақыт", regularTimetable: "Қалыпты кесте", currentTimetable: "Ағымдағы кесте", previousWeek: "Алдыңғы апта", nextWeek: "Келесі апта", received: "Алынды", authSignIn: "Microsoft арқылы кіру", authWelcome: "Қайта қош келдің", authIntroTitle: "Сенің мектеп контекстің. Оқуға арналған AI.", authIntroBody: "NIS материалдары, түсінікті түсіндірмелер, Teach Me және оқу көмегі бір кеңістікте.", authAvailable: "@akt.nis.edu.kz үшін қолжетімді", authPrivacy: "NIS AI Microsoft мектеп тіркелгісінің құпиясөзін алмайды.", authAccount: "Тіркелгі", authSchoolAccount: "Microsoft мектеп тіркелгісі", authConnected: "Қосылған", authSignOut: "Шығу", authSettings: "Профилім", authLoading: "Жұмыс кеңістігі ашылуда…", authSetup: "Microsoft арқылы кіру әлі бапталмаған.", authDomainError: "@akt.nis.edu.kz мектеп Microsoft тіркелгісін пайдалан.", authError: "Microsoft арқылы кіру аяқталмады. Қайталап көр.",
  uploadError: "Материал жүктелмеді. Қайталап көр.", fileTooLarge: "8 МБ дейінгі құжат немесе 4 МБ дейінгі сурет таңда.", invalidImage: "PNG, JPEG немесе WebP суретін таңда.", invalidFile: "Жарамды PDF, DOCX, UTF-8 TXT немесе MD таңда.", notConfigured: "ЖИ қосылмаған. Әкімшіден баптауды аяқтауды сұра.", rateLimited: "Сұраулар тым көп. Кейінірек қайталап көр.", networkError: "Байланыс үзілді. Қайталап көр.", knowledgeError: "Материалдарды алу мүмкін болмады. Қайталап көр.", limitFiles: "Кітапханада 12 файл бар.", pendingFile: "Материал өңделіп болғанша күт.", documentAttached: "Материал тіркелді", stopped: "Тоқтатылды", privacy: "Жеке сессия", noImageHistory: "Фото сақталмаған; оны қайта тірке.",
};
export const translations: Record<Language, Labels> = {
  en: { ...en, reset: "Clear profile", profileTitle: "Your context", profileSub: "", inputNote: "", schoolLibrary: "Shared materials", schoolLibrarySub: "", setupNote: "AI is not connected. Complete server setup to send messages.", notConfigured: "AI is not connected. Complete server setup." },
  ru: { ...ru, reset: "Очистить профиль", profileTitle: "Твой контекст", profileSub: "", inputNote: "", schoolLibrary: "Общие материалы", schoolLibrarySub: "", setupNote: "ИИ не подключён. Заверши настройку сервера для отправки сообщений.", notConfigured: "ИИ не подключён. Заверши настройку сервера." },
  kk: { ...kk, reset: "Профильді тазалау", profileTitle: "Сенің контекстің", profileSub: "", inputNote: "", schoolLibrary: "Ортақ материалдар", schoolLibrarySub: "", setupNote: "ЖИ қосылмаған. Хабарлама жіберу үшін серверді бапта.", notConfigured: "ЖИ қосылмаған. Серверді бапта." },
};
export function errorLabel(code: string, t: Labels) {
  return ({ NOT_CONFIGURED: t.notConfigured, FILE_TOO_LARGE: t.fileTooLarge, INVALID_FILE: t.invalidFile, UNSUPPORTED_FILE: t.invalidFile, RATE_LIMITED: t.rateLimited, FILE_LIMIT: t.limitFiles, KNOWLEDGE_ERROR: t.knowledgeError, FILE_NOT_READY: t.pendingFile } as Record<string, string>)[code] ?? t.uploadError;
}
